# Generated by Django 4.1.7 on 2023-03-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_plant_description_plant_name_plant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='plant',
            name='type',
            field=models.CharField(default='', max_length=150),
        ),
    ]
